// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2Hgkk06G_5rqe2-CTOW-RKU0z3dlso0U',
    appId: '1:428637376737:web:74b5a52e9cdfd436c7a7a0',
    messagingSenderId: '428637376737',
    projectId: 'olx-frebase',
    authDomain: 'olx-frebase.firebaseapp.com',
    storageBucket: 'olx-frebase.appspot.com',
    measurementId: 'G-WQ5VJY2NYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4H-xBRlPtrdZNokYVz57GR8c9M4SU6J8',
    appId: '1:428637376737:android:04ebe1132585f0c9c7a7a0',
    messagingSenderId: '428637376737',
    projectId: 'olx-frebase',
    storageBucket: 'olx-frebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMW2Y1SYyxyKgT-TS0ZyNDsBd4cx2m8OQ',
    appId: '1:428637376737:ios:8b2df9ecb79e37c6c7a7a0',
    messagingSenderId: '428637376737',
    projectId: 'olx-frebase',
    storageBucket: 'olx-frebase.appspot.com',
    androidClientId: '428637376737-ivvglai73s1ghv10rpr8jc0utu868c6s.apps.googleusercontent.com',
    iosClientId: '428637376737-03r17pn6i2n02vqd6er8dgtt6k0nm8e7.apps.googleusercontent.com',
    iosBundleId: 'com.example.olxfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMW2Y1SYyxyKgT-TS0ZyNDsBd4cx2m8OQ',
    appId: '1:428637376737:ios:66966693574c6813c7a7a0',
    messagingSenderId: '428637376737',
    projectId: 'olx-frebase',
    storageBucket: 'olx-frebase.appspot.com',
    androidClientId: '428637376737-ivvglai73s1ghv10rpr8jc0utu868c6s.apps.googleusercontent.com',
    iosClientId: '428637376737-5nuau61vdgh5tfno7udsveidj2l2sptg.apps.googleusercontent.com',
    iosBundleId: 'com.example.olxfirebase.RunnerTests',
  );
}
